### ISSUE TITLE
Console Logs

### ISSUE THREAD

**Issue by barisdemirezen** [hazieon/cryptomania#2]
Hey, it seems fetch responses can be seen in console. Maybe consider removing them from console log if not necessary?

**Comment by hazieon** [comment]
Wow hello haha. Yes i'll remove all console logs when i finished the
project :D i'm still working on it
Thanks !

2021年3月12日(金) 21:02 Barış Demirezen ***@***.***>:

**Comment by hazieon** [comment]
I removed the console logs now :) Thanks again!
